# Generated by Django 4.0.5 on 2022-08-03 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0005_alter_mensaje_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='leido',
        ),
    ]
