# Generated by Django 4.0.5 on 2022-07-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, default='AVATAR.jpg', null=True, upload_to=''),
        ),
    ]
