# Generated by Django 4.0.5 on 2022-07-30 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_avatar_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
